### ISSUE TITLE
Feature Request: Reroll Only

### ISSUE THREAD

**Issue by StraysFromPath** [AnchyDev/StatBoosterReroller#1]
The current reroller can add statboosts to items which don't already have them.

Our server loves the idea that the reroller can only reroll items that already have statboosts on them.

That way you still need to find/obtain your desired item with a natural statboost on it first - then you can reroll it later.

**Comment by AnchyDev** [comment]
I will look into this, also this module has been merged into StatBooster so it is no longer required to have both.

**Comment by AnchyDev** [comment]
> The current reroller can add statboosts to items which don't already have them.
> 
> Our server loves the idea that the reroller can only reroll items that already have statboosts on them.
> 
> That way you still need to find/obtain your desired item with a natural statboost on it first - then you can reroll it later.

Featured added to the StatBooster repo: https://github.com/AnchyDev/StatBooster/commit/ca3bfdb77ee3d3608bea895e09e17cf3a60d376b

**Comment by StraysFromPath** [comment]
> > The current reroller can add statboosts to items which don't already have them.
> > Our server loves the idea that the reroller can only reroll items that already have statboosts on them.
> > That way you still need to find/obtain your desired item with a natural statboost on it first - then you can reroll it later.
> 
> Featured added to the StatBooster repo: [AnchyDev/StatBooster@ca3bfdb](https://github.com/AnchyDev/StatBooster/commit/ca3bfdb77ee3d3608bea895e09e17cf3a60d376b)

Love love love this. Thank you! Is it possible that "reroll existing item" and "apply toy to item" are made into two separate item IDs?

**Comment by AnchyDev** [comment]
> > > The current reroller can add statboosts to items which don't already have them.
> > > Our server loves the idea that the reroller can only reroll items that already have statboosts on them.
> > > That way you still need to find/obtain your desired item with a natural statboost on it first - then you can reroll it later.
> > 
> > 
> > Featured added to the StatBooster repo: [AnchyDev/StatBooster@ca3bfdb](https://github.com/AnchyDev/StatBooster/commit/ca3bfdb77ee3d3608bea895e09e17cf3a60d376b)
> 
> Love love love this. Thank you! Is it possible that "reroll existing item" and "apply toy to item" are made into two separate item IDs?

You would probably need to fork the module to implement this as I don't really want to separate the functionality from the item.

**Comment by StraysFromPath** [comment]
> > > > The current reroller can add statboosts to items which don't already have them.
> > > > Our server loves the idea that the reroller can only reroll items that already have statboosts on them.
> > > > That way you still need to find/obtain your desired item with a natural statboost on it first - then you can reroll it later.
> > > 
> > > 
> > > Featured added to the StatBooster repo: [AnchyDev/StatBooster@ca3bfdb](https://github.com/AnchyDev/StatBooster/commit/ca3bfdb77ee3d3608bea895e09e17cf3a60d376b)
> > 
> > 
> > Love love love this. Thank you! Is it possible that "reroll existing item" and "apply toy to item" are made into two separate item IDs?
> 
> You would probably need to fork the module to implement this as I don't really want to separate the functionality from the item.

Sorry a misunderstanding.

One item to reroll existing statboost.

One item to add a statbooster to item.

At the moment you must choose A or B in config but access to both would be a huge upgrade.

PS: I've nearly made a full db query for all 2000 enchantments in wow with ilvl scaling so this module will be huge when i finish!
